const TUNNEL_DOMAIN = "9remote.cc";
const ZONE_ID = "34ed092484851b44d0ede479b0288738";
const SHORT_ID_LENGTH = 6;
const SHORT_ID_CHARS = "abcdefghijklmnpqrstuvwxyz23456789";

/**
 * Generate short random ID for tunnel subdomain
 */
export function generateShortId() {
  let result = "";
  for (let i = 0; i < SHORT_ID_LENGTH; i++) {
    result += SHORT_ID_CHARS.charAt(Math.floor(Math.random() * SHORT_ID_CHARS.length));
  }
  return result;
}

/**
 * Build Cloudflare API headers
 */
function buildCfHeaders(apiKey, email) {
  return {
    "Content-Type": "application/json",
    "X-Auth-Email": email,
    "X-Auth-Key": apiKey
  };
}

/**
 * Create Cloudflare Named Tunnel + DNS CNAME (DNS only, no proxy → no loop)
 * shortId is generated by CLI and passed via session
 * @returns {Promise<{tunnelId, token, hostname}>}
 */
export async function createTunnel(accountId, apiKey, email, machineId, shortId) {
  const tunnelName = `9remote-${shortId}`;
  const publicHostname = `t-${shortId}.${TUNNEL_DOMAIN}`;

  // Reuse existing tunnel if found
  const existingTunnel = await getTunnelByName(accountId, apiKey, email, tunnelName);
  if (existingTunnel) {
    console.log(`[Tunnel] Reusing existing tunnel: ${existingTunnel.id}`);

    const tokenResponse = await fetch(
      `https://api.cloudflare.com/client/v4/accounts/${accountId}/cfd_tunnel/${existingTunnel.id}/token`,
      { method: "GET", headers: buildCfHeaders(apiKey, email) }
    );
    const tokenData = await tokenResponse.json();
    if (!tokenData.success) {
      throw new Error(`Failed to get tunnel token: ${JSON.stringify(tokenData.errors)}`);
    }

    // Always upsert DNS record (recreate if deleted)
    await upsertDnsRecord(apiKey, email, shortId, existingTunnel.id);
    await configureTunnelIngress(accountId, apiKey, email, existingTunnel.id, publicHostname);

    return {
      tunnelId: existingTunnel.id,
      token: tokenData.result,
      hostname: `https://${publicHostname}`
    };
  }

  // Create new tunnel
  console.log(`[Tunnel] Creating new tunnel: ${tunnelName}`);
  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${accountId}/cfd_tunnel`,
    {
      method: "POST",
      headers: buildCfHeaders(apiKey, email),
      body: JSON.stringify({ name: tunnelName, config_src: "cloudflare" })
    }
  );

  const data = await response.json();
  if (!data.success) {
    throw new Error(`Failed to create tunnel: ${JSON.stringify(data.errors)}`);
  }

  const tunnelId = data.result.id;
  console.log(`[Tunnel] Created: ${tunnelId}`);

  // Create DNS CNAME record (DNS only - no proxy to avoid worker loop)
  await upsertDnsRecord(apiKey, email, shortId, tunnelId);

  await configureTunnelIngress(accountId, apiKey, email, tunnelId, publicHostname);

  return {
    tunnelId,
    token: data.result.token,
    hostname: `https://${publicHostname}`
  };
}

/**
 * Get tunnel by name
 */
async function getTunnelByName(accountId, apiKey, email, tunnelName) {
  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${accountId}/cfd_tunnel?name=${tunnelName}&is_deleted=false`,
    { method: "GET", headers: buildCfHeaders(apiKey, email) }
  );
  const data = await response.json();
  return data.success && data.result?.length > 0 ? data.result[0] : null;
}

/**
 * Create or update DNS CNAME record (DNS only - bypasses worker, no loop)
 */
async function upsertDnsRecord(apiKey, email, shortId, tunnelId) {
  const name = `t-${shortId}`;
  const cnameTarget = `${tunnelId}.cfargotunnel.com`;

  // Check existing record
  const findRes = await fetch(
    `https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records?type=CNAME&name=${name}.${TUNNEL_DOMAIN}`,
    { method: "GET", headers: buildCfHeaders(apiKey, email) }
  );
  const findData = await findRes.json();
  const existing = findData.success && findData.result?.length > 0 ? findData.result[0] : null;

  if (existing) {
    await fetch(
      `https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records/${existing.id}`,
      {
        method: "PATCH",
        headers: buildCfHeaders(apiKey, email),
        body: JSON.stringify({ content: cnameTarget })
      }
    );
    return;
  }

  const res = await fetch(
    `https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records`,
    {
      method: "POST",
      headers: buildCfHeaders(apiKey, email),
      body: JSON.stringify({
        type: "CNAME",
        name,
        content: cnameTarget,
        proxied: true   // Proxied - Cloudflare handles IPv4+IPv6, works on all networks
      })
    }
  );
  const resData = await res.json();
  if (!resData.success) {
    console.error("[Tunnel] Failed to create DNS record:", resData.errors);
  }
}

/**
 * Delete DNS CNAME record
 */
async function deleteDnsRecord(apiKey, email, shortId) {
  const findRes = await fetch(
    `https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records?type=CNAME&name=t-${shortId}.${TUNNEL_DOMAIN}`,
    { method: "GET", headers: buildCfHeaders(apiKey, email) }
  );
  const findData = await findRes.json();
  const existing = findData.success && findData.result?.length > 0 ? findData.result[0] : null;

  if (existing) {
    await fetch(
      `https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records/${existing.id}`,
      { method: "DELETE", headers: buildCfHeaders(apiKey, email) }
    );
  }
}

/**
 * Configure tunnel ingress rules
 */
async function configureTunnelIngress(accountId, apiKey, email, tunnelId, publicHostname) {
  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${accountId}/cfd_tunnel/${tunnelId}/configurations`,
    {
      method: "PUT",
      headers: buildCfHeaders(apiKey, email),
      body: JSON.stringify({
        config: {
          ingress: [
            { hostname: publicHostname, service: "http://localhost:2208" },
            { service: "http_status:404" }
          ]
        }
      })
    }
  );
  const data = await response.json();
  if (!data.success) {
    console.error("[Tunnel] Failed to configure ingress:", data.errors);
  }
}

/**
 * Delete Cloudflare Named Tunnel + DNS record
 */
export async function deleteTunnel(accountId, apiKey, email, tunnelId, shortId) {
  if (shortId) {
    await deleteDnsRecord(apiKey, email, shortId);
  }

  await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${accountId}/cfd_tunnel/${tunnelId}/connections`,
    { method: "DELETE", headers: buildCfHeaders(apiKey, email) }
  );

  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${accountId}/cfd_tunnel/${tunnelId}`,
    { method: "DELETE", headers: buildCfHeaders(apiKey, email) }
  );
  const data = await response.json();
  if (!data.success) {
    console.error(`[Tunnel] Failed to delete ${tunnelId}:`, data.errors);
  }
}

/**
 * Cleanup dead tunnels — called by scheduled job
 */
export async function cleanupDeadTunnels(accountId, apiKey, email) {
  const statuses = ["down", "inactive", "degraded"];
  const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000);
  let cleanedCount = 0;

  for (const status of statuses) {
    const response = await fetch(
      `https://api.cloudflare.com/client/v4/accounts/${accountId}/cfd_tunnel?is_deleted=false&status=${status}`,
      { method: "GET", headers: buildCfHeaders(apiKey, email) }
    );
    const data = await response.json();
    const tunnels = data.success ? data.result : [];

    for (const tunnel of tunnels) {
      if (!tunnel.name.startsWith("9remote-")) continue;

      const closedTimes = (tunnel.connections || [])
        .filter(c => c.closed_at)
        .map(c => new Date(c.closed_at));

      const checkTime = closedTimes.length > 0
        ? new Date(Math.max(...closedTimes))
        : new Date(tunnel.created_at);

      if (checkTime > oneHourAgo) continue;

      // Extract shortId from tunnel name: 9remote-{shortId}
      const shortId = tunnel.name.replace("9remote-", "");

      console.log(`[Cleanup] Dead tunnel: ${tunnel.name} (${tunnel.status})`);
      try {
        await deleteTunnel(accountId, apiKey, email, tunnel.id, shortId);
        cleanedCount++;
      } catch (error) {
        console.error(`[Cleanup] Failed to delete ${tunnel.name}:`, error);
      }
    }
  }

  return cleanedCount;
}
