import { Server } from "socket.io";
import { readFileSync } from "fs";
import { join } from "path";
import { initSignalingGlobal, stopSignalingGlobal, setOfferFallback, sendSignaling, dropPending, pendingPeersOf, onSignalingReady, hasPendingOffer, retrySignalingNow } from "../lib/signalingGlobal.js";
import { HostBus } from "./HostBus.js";
import { PATHS, LOCAL_UI_ORIGINS, LOCAL_UI_DEVICE_ID } from "../lib/constants.js";
import { verifyLocalToken } from "../lib/localToken.js";
import { isSitesHost } from "../lib/sitesHost.js";
import { ProtocolManager } from "./ProtocolManager.js";
import { SIGNALING_ERRORS } from "../lib/transportConstants.js";
import { registerProtocol, unregisterProtocol, activeProtocols, disableAllRtc, notifyRtcEnabled, setRtcSessionKiller, disposeProtocol } from "./broadcast.js";
import { REMOTE_CONFIG } from "../features/remote/REMOTE_CONFIG.js";
import { loadSettings } from "../cli/utils/state.js";
import { setupTerminalSocket, setupTerminalHandlers } from "../features/terminal/terminalSocket.js";
import { checkRemoteAvailable } from "../features/remote/remoteSocket.js";
import { setupFileExplorerHandlers } from "../features/fileExplorer/fileExplorerSocket.js";
import { setupClipboardHandlers } from "../features/clipboard/clipboardSocket.js";
import { setupQuotaTrackerHandlers } from "../features/quotaTracker/quotaTrackerSocket.js";
import { setupBackgroundHandlers } from "../features/terminal/backgroundSocket.js";
import { setupAiHandlers } from "../features/ai/aiSocket.js";
import { setupJarvisHandlers } from "../features/jarvis/jarvisSocket.js";
import { trackConnection, untrackConnection, pushUiLog, pushUiLogDebug, clearOneTimeKey, pushUiEvent, setRemoteAvailable, pushTransportState, getTunnelPayload } from "../api/ui.js";
import {
  loadApprovedDevices,
  isDevicePending,
  gateDevice,
  approveDevice,
  approveDeviceSession,
  isDeviceKicked,
  addPendingApproval,
  removePendingApproval,
  getPendingApproval,
  getPendingSocketId,
  markDeviceRejected,
  updateRejectedSocket,
  clearRejectedDevice,
  loadAutoApprove
} from "../lib/deviceApproval.js";
import { admissionGate, submitTailProof, noteTailFailure, presentedTailOf, finishTailRejection, handleTailProof, verdictStateOf, onTailProven, clearProofWaiters, PROOF_DEADLINE, verifyKeyTail } from "../lib/deviceAuth.js";
import { openSealedTail } from "../lib/hostKey.js";
import { ADMISSION, DEVICE_GATE, TAIL_VERDICT, TAIL_REJECT_REASON, CHANNELS } from "../lib/transportConstants.js";
import { headOf, tailOf } from "../cli/utils/apiKey.js";
import { createLogger } from "../lib/logger.js";
import { ConnectionRegistry } from "./ConnectionRegistry.js";
import { planAdmission } from "./admissionFlow.js";
import { AUTH_EVENTS, CONNECTION_STATE } from "../lib/connectionConstants.js";

// pushUiLog never reaches agent.log, where these decisions must be readable later.
const logger = createLogger("transport");

function loadApiKey() {
  try {
    const keysFile = join(PATHS.ROOT, "keys.json");
    const data = JSON.parse(readFileSync(keysFile, "utf8"));
    return data.key || null;
  } catch {
    return null;
  }
}

// Re-read cadence: keys.json can be regenerated by the separate CLI process.
const KEY_WATCH_INTERVAL_MS = 5000;

let ioInstance = null;

export function getIO() {
  return ioInstance;
}

// Both hosts answer the same carrier question, so new protocols need no per-call-site type checks.
function carrierOf(socket) {
  return socket.carrier || {
    id: "ws",
    ip: socket.handshake?.headers?.["x-forwarded-for"] || socket.handshake?.address || "unknown",
    pendingId: socket.id
  };
}

function authOf(socket) {
  return socket?.data?.auth || socket?.handshake?.auth || null;
}

// One gate for every carrier; signaling has no socket and presents no tail.
function askGate(socket, deviceId) {
  const presented = socket
    ? presentedTailOf(authOf(socket), openSealedTail)
    : undefined;
  const verdict = admissionGate(deviceId, presented, {
    provenSocket: socket?.data?.provenDevice === true,
    // A QR pairing has no tail yet; the live one-time code carries gate 1.
    tempKey: authOf(socket)?.tempKey || null
  });
  logger.info(`gate: device=${deviceId?.slice(0, 8) ?? "none"} step=${verdict.step} ` +
    `decision=${verdict.decision}${verdict.reason ? ` reason=${verdict.reason}` : ""} ` +
    `carrier=${socket ? carrierOf(socket).id : "signaling"}`);
  // Record verdicts once for all carriers; a pairing's secret is the CODE's tail, not the key's.
  const pairing = !!authOf(socket)?.tempKey;
  const carriedByTail = verdict.step === "authz" && !pairing;
  if (socket && presented !== undefined && (carriedByTail || verdict.step === "auth")) {
    submitTailProof(deviceId, presented, { pairing, tempKey: authOf(socket)?.tempKey || null }); // records proven or rejected, once
  }
  if (socket && verdict.decision === ADMISSION.reject && verdict.step === "auth") {
    // penaltyMs comes from the shared counter, so a guess stays expensive.
    socket.data.tailReject = socket.data.tailReject
      || { reason: verdict.reason, penaltyMs: noteTailFailure(headOf(loadApiKey() || "")) };
  }
  return verdict;
}

// Once per socket: the flow re-enters on every proof, and a second copy would double-charge the guess counter.
function registerAuthHandlers(socket) {
  if (socket.data.authHandlersReady) return;
  socket.data.authHandlersReady = true;
  socket.on("device:tailProof", (data) => {
    const deviceId = authOf(socket)?.deviceId;
    if (data?.tempKey && socket.data) {
      if (!socket.data.auth) socket.data.auth = {};
      socket.data.auth.tempKey = data.tempKey;
    }
    // The RTC dispatcher swallows thrown errors, so guard here.
    try {
      const ok = handleTailProof(socket, data);
      logger.info(`tailProof: device=${deviceId?.slice(0, 8)} carrier=${carrierOf(socket).id} accepted=${ok}`);
      if (!ok) rejectDeviceTail(socket, deviceId);
    } catch (e) {
      logger.warn(`tailProof handler failed: ${e.message}`);
    }
  });
}

/** Bus must be ready before handlers (first tile frame drops) and "terminal:ready" ends the getSessions race. */
async function setupSocketFeatures(socket) {
  if (authOf(socket)?.tempKey) {
    logger.info("one-time key used — clearing from UI");
    clearOneTimeKey();
  }
  await attachTransportBus(socket);
  registerAuthHandlers(socket);
  // One admission flow for every protocol: gate answers, planAdmission plans, this applies.
  if (!socket.data.localUi) {
    const deviceId = authOf(socket)?.deviceId || null;
    const conn = connectionFor(socket);
    if (!conn) return;
    // Attach this socket's carrier, not the PM: conn.connected checks per-carrier bytes.
    const { id: carrierId } = carrierOf(socket);
    conn.attach(carrierId, socket.data.protocol?._adapters?.get(carrierId) || null);

    const verdict = askGate(socket, deviceId);
    const { effects, reason } = planAdmission(conn, verdict);
    logger.info(`flow: device=${deviceId?.slice(0, 8)} state=${conn.state} ` +
      `effects=[${effects.join(",")}]${reason ? ` reason=${reason}` : ""}`);
    pushUiLog(`[auth] ${deviceId?.slice(0, 8)}: ${conn.state} → ${effects.join(",") || "wait"}`);

    if (effects.includes("refuse")) {
      rejectDeviceTail(socket, deviceId, reason);
      return;
    }
    // The proof rides the channel the live auth handlers listen on; re-enter when it lands.
    if (effects.includes("open-auth-channel")) {
      if (!socket.data.awaitingProof) {
        socket.data.awaitingProof = true;
        onTailProven(deviceId, () => {
          socket.data.awaitingProof = false;
          if (socket.connected) setupSocketFeatures(socket).catch(() => {});
        }, () => rejectDeviceTail(socket, deviceId, TAIL_REJECT_REASON.timeout));
      }
      return;
    }
    // Key proven, host not yet asked: ask once per device; releaseDevice re-enters here.
    if (effects.includes("ask-host")) {
      const carrier = carrierOf(socket);
      askHostToApprove(deviceId, {
        socketId: carrier.pendingId,
        ip: carrier.ip,
        peerId: socket.peerId,
        notify: () => verdictEmit(socket, "device:pendingApproval")
      });
      return;
    }
    if (!effects.includes("start-session")) return;
    // The gate is pure — this is where auto-approve is recorded, or the client stays invisible.
    if (gateDevice(deviceId) === DEVICE_GATE.auto) {
      approveDevice(deviceId);
      clearRejectedDevice(deviceId);
      pushUiEvent("deviceApproval", { action: "refresh" });
    }
  }
  await setupSessionFeatures(socket);
}

function issueKeyToPairedDevice(socket) {
  if (!authOf(socket)?.tempKey) return;
  const tail = tailOf(loadApiKey() || "");
  if (!tail) return;
  onClientReady(socket, () => {
    verdictEmit(socket, "device:keyIssued", { tail });
    logger.info(`key issued to paired device=${authOf(socket)?.deviceId?.slice(0, 8)}`);
  });
}

function syncClientSession(socket) {
  if (!socket.connected) return;
  if (!socket.data?.conn?.active && !socket.data?.localUi) return;
  if (!socket.data?.clientReady) return;

  announceAdmitted(socket);
  issueKeyToPairedDevice(socket);
  const info = setupTerminalSocket._buildServerInfo?.();
  if (info) socket.emit("serverInfo", info);
  socket.emit("srvCaps", { env2: 1, fragCtl: 1 });
  socket.emit("tunnel:updated", getTunnelPayload());
}

/** Reached only after both gates pass; held RTC sessions resume here without re-registering auth handlers. */
async function setupSessionFeatures(socket) {
  if (socket.data.sessionReady) return;
  socket.data.sessionReady = true;
  // Legacy mirror of conn.active for code that still reads socket.data.approved.
  socket.data.approved = true;
  setupFileExplorerHandlers(socket);
  setupClipboardHandlers(socket);
  setupQuotaTrackerHandlers(socket);
  setupBackgroundHandlers(socket);
  setupAiHandlers(socket, ioInstance);
  setupJarvisHandlers(socket);
  await setupTerminalHandlers(socket, ioInstance, loadApiKey());
  syncClientSession(socket);
  socket.emit("terminal:ready");
}

/** Await pm.init(): the ws adapter must exist before tiles stream, or the first frame drops. */
async function attachTransportBus(socket) {
  if (socket.data.protocol) return;
  const { webrtc, streaming } = REMOTE_CONFIG;
  const pm = new ProtocolManager(socket, {
    enableWebRTC: webrtc.enableWebRTC,
    enableTurn: webrtc.enableTurn ?? false,
    apiKey: headOf(loadApiKey()),
    turnApiUrl: webrtc.turnApiUrl || null,
    turnRefreshInterval: webrtc.turnRefreshInterval,
    dcMaxMessageSize: webrtc.dcMaxMessageSize,
    dcChunkSize: webrtc.dcChunkSize,
    dcMaxTilesPerFrame: webrtc.dcMaxTilesPerFrame,
    answerTimeout: webrtc.answerTimeout,
    maxControlBuffer: webrtc.maxControlBuffer,
    wsChunkSize: streaming.chunkSize,
    // DO signaling relay — room = client deviceId, gated by apiKey on the Worker.
    signaling: {
      // Must be peerId (deviceId:tab): offers arrive from=peerId, and a key miss spawns a duplicate PM.
      deviceId: socket.peerId || authOf(socket)?.peerId || authOf(socket)?.deviceId || null,
      doUrl: webrtc.signalingDoUrl,
      apiKey: loadApiKey()
    }
  });
  socket.data.protocol = pm;
  // HostBus (RTC-first) session: RTC dying with no WS fallback means it is over.
  if (socket.defersWsAdapter) {
    pm._onDead = () => {
      logger.debug(`[diag] _onDead fired peer=${(socket.peerId || "").slice(0, 12)} — rtc never returned in grace`);
      pushUiLogDebug(`RTC session closed: ${authOf(socket)?.deviceId?.slice(0, 8)}...`);
      try { pm.close(); } catch {}
      unregisterProtocol(pm);
      socket.disconnect();
    };
  }
  registerProtocol(pm);
  pm.attachAsBus(socket);
  try {
    await pm.init(); // also arms DO signaling (no gap between the two)
  } catch (e) {
    console.error("[transport] pm init failed:", e.message);
  }
}

// RTC-only HostBus instances keyed by peerId; the connection itself lives in ConnectionRegistry.
const rtcSessions = new Map();

// One session book for every protocol: admission, gating and teardown all read from it.
const connections = new ConnectionRegistry();

/** The web↔host connection (not a terminal session), created on first sight of the device. */
function connectionFor(socket) {
  const deviceId = authOf(socket)?.deviceId || null;
  if (!deviceId) return null;
  const peerId = socket.peerId || authOf(socket)?.peerId || deviceId;
  const existing = socket.data.conn;
  if (existing && !existing.closed) return existing;
  const conn = connections.open({ deviceId, peerId, apiKey: loadApiKey() });
  socket.data.conn = conn;
  return conn;
}

// Debug toggle: refuse RTC so clients fall back to the tunnel (fallback-path testing).
let rtcTestDisabled = false;

export function isRtcTestDisabled() { return rtcTestDisabled; }
export function setRtcTestDisabled(disabled) {
  rtcTestDisabled = disabled;
  if (!disabled) {
    // RTC re-enabled: tell clients to clear their stop-retry flag and renegotiate.
    notifyRtcEnabled();
    return;
  }
  // RTC lives inside each PM now — tear it down across all of them so clients fall back to WS.
  disableAllRtc();
  // Also clear HostBus RTC sessions (RTC-first offer-before-WS case).
  for (const peerId of [...rtcSessions.keys()]) {
    killRtcSession(peerId);
    pushUiLogDebug(`RTC test-disabled: killed session ${peerId?.slice(0, 8)}`);
  }
}

// Synthetic socketId giving RTC peers the same pending-approval key shape as socket.io.
const rtcSocketId = (peerId) => `rtc-${peerId}`;
const rtcPeerId = (socketId) => (socketId.startsWith("rtc-") ? socketId.slice(4) : null);
const sendSignalingTo = (peerId, msg) => sendSignaling({ ...msg, to: peerId });

// clientReady can beat route()'s grace wait; the flag is stamped at connection so a late once() won't miss it.
function onClientReady(socket, fn) {
  if (socket.data.clientReady) fn();
  else socket.once("device:clientReady", fn);
}

// Armed before any traffic; an early clientReady (RTC-first) is re-announced once the session turns active.
function armClientReady(socket) {
  socket.data.clientReady = false;
  socket.on("device:clientReady", () => {
    socket.data.clientReady = true;
    syncClientSession(socket);
  });
}

/** Route a DO-signaling offer through the shared gate — same admit/hold/reject as the socket.io path. */
function handleRtcOffer(peerId) {
  if (!peerId) return;
  // Remote is off — RTC is a remote carrier too, so the offer dies here. The
  // relay itself is already stopped; this covers an offer already in flight.
  if (!isRemoteEnabled()) {
    sendSignalingTo(peerId, { type: "error", message: "remote-disabled" });
    return;
  }
  if (rtcTestDisabled) {
    sendSignalingTo(peerId, { type: "error", message: "rtc-disabled" });
    return;
  }
  // peerId = "deviceId:tab" — one session per tab, approval per device.
  const deviceId = peerId.split(":")[0];

  const existing = rtcSessions.get(peerId);
  if (existing) {
    // Still-building sessions own the offer too; only a closed PM is stale.
    if (!existing.data.protocol?._closed) return;
    pushUiLogDebug(`Stale RTC session ${deviceId.slice(0, 8)} — rebuilding`);
    killRtcSession(peerId);
  }

  // A live WS socket will consume the buffered offer; spawning here would duplicate the PM.
  const hasWsHost = hasLiveWsForPeer(peerId);

  // Same gate as socket.io; signaling has no handshake, so a stranger lands on reject — not the modal.
  const verdict = askGate(null, deviceId);

  // A key-hold is neither refusal nor a host question: the proof rides the very channel this session opens.
  if (verdict.decision === ADMISSION.hold && verdict.step === "auth") {
    if (hasWsHost) return;
    logger.info(`rtc-offer: building session so the TAIL proof has a road device=${deviceId.slice(0, 8)}`);
    return void startRtcSession(peerId, deviceId);
  }

  switch (verdict.decision) {
    case ADMISSION.admit:
      if (hasWsHost) return;
      return void startRtcSession(peerId, deviceId);

    case ADMISSION.reject:
      updateRejectedSocket(deviceId, rtcSocketId(peerId), "rtc");
      sendSignalingTo(peerId, { type: "error", message: SIGNALING_ERRORS.rejected });
      dropPending(peerId); // nothing will consume it — don't hold the SDP in RAM
      pushUiLog(`Rejected device via RTC: ${deviceId.slice(0, 8)} — waiting in Clients list`);
      pushUiEvent("deviceApproval", { action: "refresh" });
      return;

    default:
      // Unknown device: the offer stays buffered in signalingGlobal, and signaling is the only channel to say "waiting".
      askHostToApprove(deviceId, {
        socketId: rtcSocketId(peerId),
        ip: "rtc",
        peerId,
        notify: () => sendSignalingTo(peerId, { type: "error", message: SIGNALING_ERRORS.pending })
      });
  }
}

/** One approval ask for both carriers; they differ only in notify(). Key is already proven here. */
function askHostToApprove(deviceId, { socketId, ip, peerId, notify }) {
  notify();
  // Approval is per device: a second tab or carrier joins the entry already up.
  if (isDevicePending(deviceId)) {
    pushUiLog(`[auth] already pending, not asking twice: ${deviceId?.slice(0, 8)}`);
    return;
  }
  addPendingApproval(socketId, { deviceId, ip, ...(peerId ? { peerId } : {}) });
  logger.info(`asking host: device=${deviceId?.slice(0, 8)} via=${peerId ? "rtc" : "ws"}`);
  pushUiLog(`[auth] ASKING HOST: ${deviceId?.slice(0, 8)} via=${peerId ? "rtc" : "ws"} socketId=${socketId}`);
  pushUiLog(`Device needs approval: ${deviceId?.slice(0, 8) || "no-id"}`);
  pushUiEvent("deviceApproval", { socketId, deviceId, ip, action: "pending" });
}

function hasLiveWsForPeer(peerId) {
  for (const s of ioInstance?.sockets.sockets.values() || []) {
    if (s.connected && authOf(s)?.peerId === peerId) return true;
  }
  return false;
}

// One-shot verdicts must survive a flaky carrier: prefer the PM's every-carrier send.
function verdictEmit(socket, event, ...args) {
  const pm = socket.data?.protocol;
  if (pm && !pm._closed && pm.emitEverywhere(event, ...args)) return;
  socket.emit(event, ...args);
}

function announceAdmitted(socket) {
  const say = () => {
    if (!socket.connected) return;
    onClientReady(socket, () => verdictEmit(socket, "device:approved"));
  };
  // The local UI is trusted by token and has no device to gate.
  if (socket.data.localUi) return say();

  // "approved" shows the workspace, so it may only follow an ACTIVE session — looked up when due, not now.
  const conn = socket.data.conn;
  if (conn?.active) return say();
  if (conn) return void conn.on("state", function onState(e) {
    if (e.to === CONNECTION_STATE.closed) conn.off("state", onState);
    if (e.to !== CONNECTION_STATE.active) return;
    conn.off("state", onState);
    say();
  });
  // No session yet: setupSessionFeatures makes one active and announces from there.
}

function unlockSocket(socket) {
  if (socket.data.approved || socket.data.unlocking) return Promise.resolve();
  // setupSessionFeatures sets approved once both gates pass — never here.
  socket.data.unlocking = true;
  announceAdmitted(socket);
  const done = setupSocketFeatures(socket)
    .catch((e) => pushUiLog(`Feature setup failed: ${e.message}`))
    .finally(() => { socket.data.unlocking = false; });
  return done;
}

/** WS unlocks first to consume buffered offers; only leftovers spawn RTC-only sessions (no double-PM). */
async function releaseDevice(deviceId) {
  if (!deviceId) return;
  const key = getPendingSocketId(deviceId);
  if (key) removePendingApproval(key);
  const setups = [];
  for (const socket of ioInstance?.sockets.sockets.values() || []) {
    if (authOf(socket)?.deviceId !== deviceId || socket.data.approved) continue;
    setups.push(unlockSocket(socket));
  }
  // Held RTC sessions need no spawning, only the flow re-entered (second gate re-asked).
  for (const vs of rtcSessions.values()) {
    if (authOf(vs)?.deviceId !== deviceId || vs.data.approved) continue;
    setups.push(setupSocketFeatures(vs).catch((e) => pushUiLog(`Connection resume failed: ${e.message}`)));
  }
  await Promise.allSettled(setups);
  for (const peerId of pendingPeersOf(deviceId)) startRtcSession(peerId, deviceId);
}

/** Answer the client before closing its carriers — any other order cuts the channel first. */
function rejectDeviceTail(socket, deviceId, reason) {
  logger.debug(`[diag] rejectDeviceTail device=${deviceId?.slice(0, 8)} reason=${reason}`);
  socket.data.tailReject = socket.data.tailReject || { reason, penaltyMs: 0 };
  const why = socket.data.tailReject.reason;
  logger.warn(`tail rejected (${why}): device=${deviceId?.slice(0, 8) ?? "none"} carrier=${carrierOf(socket).id}`);
  pushUiLog(`Device refused (${why}): ${deviceId?.slice(0, 8)}`);
  // Only a mismatch burns a pairing code (here and at the Worker); timeout leaves it alive.
  if (authOf(socket)?.tempKey && why === TAIL_REJECT_REASON.mismatch) {
    logger.warn("one-time key burned (wrong TAIL) — clearing from UI");
    clearOneTimeKey();
  }
  finishTailRejection(socket, () => {
    if (socket.defersWsAdapter) killRtcSession(socket.peerId);
    revokeDevice(deviceId, why);
  });
}

/** Mirror of releaseDevice: a failed proof must close every carrier the device holds. */
function revokeDevice(deviceId, reason) {
  logger.debug(`[diag] revokeDevice device=${deviceId?.slice(0, 8)} reason=${reason}`);
  if (!deviceId) return;
  clearProofWaiters(deviceId);
  removePendingApproval(getPendingSocketId(deviceId) || "");
  // One call reaches every tab and every protocol the device holds.
  connections.closeDevice(deviceId, reason);
  for (const socket of ioInstance?.sockets.sockets.values() || []) {
    if (authOf(socket)?.deviceId !== deviceId) continue;
    socket.data.tailReject = socket.data.tailReject || { reason, penaltyMs: 0 };
    finishTailRejection(socket);
  }
  // finishTailRejection answers on a timer; killing here would cut the channel first — let it close them.
  for (const [peerId, session] of rtcSessions) {
    if (authOf(session)?.deviceId !== deviceId) continue;
    if (session.data?.tailReject) continue; // already answering, will close itself
    killRtcSession(peerId);
  }
}

/** Approvals move between carriers, so an exact-id miss falls back to the device's entry. */
function resolvePending(socketId) {
  const direct = getPendingApproval(socketId);
  if (direct) return { key: socketId, ...direct };
  const deviceId = rtcPeerId(socketId)?.split(":")[0]
    || (authOf(ioInstance?.sockets.sockets.get(socketId) || null))?.deviceId
    || null;
  const key = deviceId ? getPendingSocketId(deviceId) : null;
  const entry = key ? getPendingApproval(key) : null;
  return entry ? { key, ...entry } : null;
}

function killRtcSession(peerId) {
  const session = peerId ? rtcSessions.get(peerId) : null;
  if (!session) return;
  const pm = session.data?.protocol;
  rtcSessions.delete(peerId);
  try { session.disconnect(); } catch {}
  if (pm) { try { pm.close(); } catch {} unregisterProtocol(pm); }
}
// broadcast.disposeProtocol hands PM disposal back here for the session part.
setRtcSessionKiller(killRtcSession);

/** Fire-and-forget build — every caller is a sync signaling/approval path. */
function startRtcSession(peerId, deviceId) {
  buildRtcSession(peerId, deviceId).catch((e) => {
    killRtcSession(peerId);
    pushUiLog(`RTC session failed: ${e.message}`);
  });
}

async function buildRtcSession(peerId, deviceId) {
  if (rtcSessions.has(peerId)) return;
  const socket = new HostBus({ deviceId, peerId, apiKey: loadApiKey() });
  // The carrier exists so the device can prove its key; admission is the session's separate answer.
  socket.data.approved = false;
  socket.data.rtcSession = true;
  socket.data.conn = connections.open({ deviceId, peerId, apiKey: loadApiKey() });
  armClientReady(socket);
  // Published before its PM exists — wait on this; .data.protocol would silently no-op.
  let markReady;
  socket.data.ready = new Promise((resolve) => { markReady = resolve; });
  rtcSessions.set(peerId, socket);
  trackConnection(socket.id, "rtc", deviceId, "rtc");
  socket.on("disconnect", () => {
    logger.debug(`[diag] HostBus disconnect peer=${(peerId || "").slice(0, 12)} → untrack + conn.close`);
    if (rtcSessions.get(peerId) === socket) rtcSessions.delete(peerId);
    untrackConnection(socket.id);
    // The connection dies with its last carrier, or a closed browser stays "online".
    socket.data.conn?.close("carrier-gone");
    markReady(); // never leave a waiter hanging on a dead session
  });
  pushUiLogDebug(`RTC session: ${deviceId.slice(0, 8)}...`);
  try {
    await setupSocketFeatures(socket);
  } finally {
    markReady();
  }
  // No handshake carries a TAIL, so arm the deadline unconditionally; proven devices no-op on it.
  setTimeout(() => {
    if (rtcSessions.get(peerId) !== socket) return;
    if (verdictStateOf(deviceId) === TAIL_VERDICT.proven) return;
    pushUiLog(`Device never proved its TAIL: ${deviceId.slice(0, 8)} — dropping session`);
    rejectDeviceTail(socket, deviceId, TAIL_REJECT_REASON.timeout);
  }, PROOF_DEADLINE + 1000);
  // The client's "accepted" signal — only once the TAIL is proven, never inside the proof window.
  announceAdmitted(socket);
}

/** Approve a pending device — one path for both carriers (resolvePending handles stale modal ids). */
export function approveSocketDevice(socketId) {
  if (!ioInstance) return false;
  const pending = resolvePending(socketId);
  if (!pending) return false;

  // Approving cannot override the key, or it reads as "approve, then instant kick".
  if (verdictStateOf(pending.deviceId) === TAIL_VERDICT.rejected) {
    logger.warn(`approve refused — TAIL was rejected: device=${pending.deviceId.slice(0, 8)}`);
    pushUiLog(`Cannot approve ${pending.deviceId.slice(0, 8)} — wrong access key`);
    removePendingApproval(pending.key);
    revokeDevice(pending.deviceId, TAIL_REJECT_REASON.mismatch);
    pushUiEvent("deviceApproval", { action: "refresh" });
    return false;
  }

  approveDevice(pending.deviceId);
  clearRejectedDevice(pending.deviceId);
  pushUiLog(`Device approved: ${pending.deviceId.slice(0, 8)}...`);

  releaseDevice(pending.deviceId); // also clears the device's pending entry
  pushUiEvent("deviceApproval", { action: "refresh" });
  return true;
}

export function approveRejectedDevice(deviceId) {
  if (!ioInstance || !deviceId) return false;

  approveDevice(deviceId);
  clearRejectedDevice(deviceId);
  pushUiLog(`Device approved from pending: ${deviceId.slice(0, 8)}...`);

  releaseDevice(deviceId);
  pushUiEvent("deviceApproval", { action: "refresh" });
  return true;
}

/** Sockets only — the device itself stays approved. */
export function disconnectDeviceSockets(deviceId) {
  logger.debug(`[diag] disconnectDeviceSockets device=${deviceId?.slice(0, 8)} — stack hint: ${new Error().stack.split("\n")[2]?.trim()?.slice(0, 90)}`);
  const io = ioInstance;
  if (!io || !deviceId) return 0;
  let count = 0;
  for (const socket of io.sockets.sockets.values()) {
    if (authOf(socket)?.deviceId === deviceId) {
      socket.disconnect(true);
      count++;
    }
  }
  // A PM may outlive its socket's disconnect (remote grace) — close it now or the client never re-requests approval.
  for (const pm of activeProtocols()) {
    if (pm._closed) continue;
    if (pm._deviceId?.split(":")[0] !== deviceId) continue;
    disposeProtocol(pm);
    count++;
  }
  // RTC-only sessions have no socket.io entry — kill them by peerId prefix.
  for (const [peerId, vs] of rtcSessions) {
    if (peerId.split(":")[0] !== deviceId) continue;
    try { vs.data.protocol?.close(); } catch {}
    unregisterProtocol(vs.data.protocol);
    dropPending(peerId);
    vs.disconnect();
    count++;
  }
  if (count) pushUiLogDebug(`Disconnected ${count} socket(s) for device ${deviceId.slice(0, 8)}...`);
  return count;
}

/** Notifies both carriers; the rejection is remembered in RAM for the Clients list. */
export function rejectSocketDevice(socketId) {
  if (!ioInstance) return false;

  const pending = resolvePending(socketId);
  const socket = ioInstance.sockets.sockets.get(socketId);
  removePendingApproval(pending?.key || socketId);

  if (pending?.deviceId) {
    markDeviceRejected(pending.deviceId, { ip: pending.ip, socketId });
  }

  if (socket) {
    verdictEmit(socket, "device:rejected");
    socket.disconnect(true);
  }

  // RTC peer — no socket to notify; answer over DO and drop the buffered offer.
  const peerId = pending?.peerId || rtcPeerId(socketId);
  if (peerId) {
    sendSignalingTo(peerId, { type: "error", message: SIGNALING_ERRORS.rejected });
    dropPending(peerId);
  }

  pushUiEvent("deviceApproval", { action: "refresh" });
  pushUiLog(`Device rejected: ${pending?.deviceId?.slice(0, 8) || "unknown"}...`);
  return true;
}

/** Remote access switch — persisted in settings.json, default ON (fresh install). */
export function isRemoteEnabled() {
  return loadSettings().remoteEnabled !== false;
}

function isLoopbackSocket(socket) {
  const addr = socket.handshake?.address || "";
  return addr === "127.0.0.1" || addr === "::1" || addr === "::ffff:127.0.0.1";
}

/** A request from this machine is not remote access — the workspace on localhost
 *  is the user's own session and must outlive the switch. Address alone cannot
 *  tell them apart: cloudflared runs on this machine, so tunnel traffic lands on
 *  loopback too. The cf-connecting-ip header is what gives the outside away. */
function isLocalSocket(socket) {
  if (socket.handshake?.headers?.["cf-connecting-ip"]) return false;
  return isLoopbackSocket(socket);
}

/** Runtime side of the switch: off drops every remote client and the DO relay
 *  (local UI sockets stay); on re-arms the relay. Persisting is the caller's job. */
export function setRemoteEnabled(enabled) {
  if (enabled) {
    initSignalingGlobal(headOf(loadApiKey()));
    // PMs that outlived the switch kept a dead handler registration — re-arm
    // them (same as the rtc test toggle), or the next offer finds no PM and
    // spawns a duplicate RTC-only session.
    notifyRtcEnabled();
    return;
  }
  stopSignalingGlobal();
  // stopSignalingGlobal drops the handler map, but a PM still holds the cleanup
  // and its setupSignaling guard would refuse to re-register — release it here.
  for (const pm of activeProtocols()) {
    if (pm._closed) continue;
    try { pm._offGlobalSig?.(); } catch {}
    pm._offGlobalSig = null;
  }
  const io = ioInstance;
  const localPms = new Set();
  if (io) {
    for (const socket of io.sockets.sockets.values()) {
      // Local UI and the loopback workspace are not remote — keep both.
      if (socket.data.localUi || isLocalSocket(socket)) {
        if (socket.data.protocol) localPms.add(socket.data.protocol);
        continue;
      }
      socket.disconnect(true);
    }
  }
  // A PM may outlive its socket's disconnect (remote grace) — close it now.
  for (const pm of activeProtocols()) {
    if (pm._closed || localPms.has(pm)) continue;
    disposeProtocol(pm);
  }
  // RTC-only sessions have no socket.io entry — kill them by peerId.
  for (const [peerId, vs] of rtcSessions) {
    try { vs.data.protocol?.close(); } catch {}
    unregisterProtocol(vs.data.protocol);
    dropPending(peerId);
    vs.disconnect();
  }
}

export async function startTransportServer(server) {
  loadApprovedDevices();
  loadAutoApprove();

  // Join the signaling room at boot so RTC can establish before the tunnel is up.
  if (isRemoteEnabled()) initSignalingGlobal(headOf(loadApiKey()));
  // The TUI regenerates the key in a separate process; re-reading keeps the room in sync.
  setInterval(() => {
    if (!isRemoteEnabled()) return;
    const key = headOf(loadApiKey());
    if (key) initSignalingGlobal(key);
  }, KEY_WATCH_INTERVAL_MS);
  // Offer with no PM → build an RTC-only session so login works without a tunnel.
  setOfferFallback(handleRtcOffer);
  onSignalingReady(() => pushTransportState());

  const io = new Server(server, {
    cors: {
      origin: "*",
      methods: ["GET", "POST"],
      credentials: true,
      allowedHeaders: ["*"]
    },
    // Same-port sites host is untrusted; refusing at the handshake covers polling too.
    allowRequest: (req, callback) => callback(null, !isSitesHost(req.headers.host)),
    transports: ["websocket", "polling"],
    allowEIO3: true,
    allowUpgrades: true,
    // Stale-entry window vs mobile-stall tolerance — halved from 25s/60s; pagehide (web) covers clean closes.
    pingTimeout: 30000,
    pingInterval: 12000,
    maxHttpBufferSize: 1e8,
    perMessageDeflate: { threshold: 1024 }
  });

  const hasRemote = await checkRemoteAvailable();
  setRemoteAvailable(hasRemote);

  io.on("connection", (socket) => {
    // The network is up — revive the DO relay if it gave up during boot.
    retrySignalingNow("client-connected");
    const ip = socket.handshake.headers["x-forwarded-for"] || socket.handshake.address || "unknown";
    const deviceId = authOf(socket)?.deviceId || null;

    armClientReady(socket);

    socket.data.approved = false;
    // Inactive sessions carry auth events only; HostBus.listeners() enforces the same on RTC.
    socket.use((packet, next) => {
      // The local UI is trusted by token, not by session, and never has one.
      if (socket.data.localUi) return next();
      const conn = socket.data.conn;
      // No session yet: only auth events pass — they are what creates the session.
      if (!conn) return AUTH_EVENTS.has(packet[0])
        ? next()
        : next(new Error("Device not approved"));
      if (conn.allows(packet[0])) return next();
      return next(new Error("Device not approved"));
    });

    // Local UI trust = token + loopback + origin; resists CSWSH token theft.
    const isLoopback = isLoopbackSocket(socket);
    const isTunnel = !!socket.handshake.headers["cf-connecting-ip"];
    const origin = socket.handshake.headers.origin;
    const originOk = !origin || LOCAL_UI_ORIGINS.includes(origin);
    if (!isTunnel && isLoopback && originOk && verifyLocalToken(socket.handshake.auth?.localToken)) {
      socket.data.approved = true;
      socket.data.localUi = true;
      pushUiLogDebug("Local UI connected — trusted (token)");
      setupSocketFeatures(socket).catch((e) => pushUiLog(`Feature setup failed: ${e.message}`));
      return; // do not track in Clients list
    }

    // Reserved local-ui deviceId that failed trust check → spoof attempt, reject.
    if (deviceId === LOCAL_UI_DEVICE_ID) {
      pushUiLog(`Rejected untrusted local-ui socket from ${ip}`);
      socket.disconnect(true);
      return;
    }

    // Remote is switched off: rejecting here (not only disconnecting existing
    // sockets) is what actually keeps new clients out — a reconnect would
    // otherwise sail straight past the switch. The local workspace is not remote
    // and must keep working, so only requests from outside are turned away.
    if (!isRemoteEnabled() && !isLocalSocket(socket)) {
      pushUiLogDebug(`Rejected ${deviceId?.slice(0, 8) || "unknown"} from ${ip} — remote access is off`);
      socket.disconnect(true);
      return;
    }

    // Loopback workspace presents the host's own key TAIL: session-scoped admit only (never persisted, never for kicked devices).
    if (!isTunnel && isLoopback && originOk && deviceId && !isDeviceKicked(deviceId)) {
      const presentedLoopback = presentedTailOf(authOf(socket), openSealedTail);
      if (presentedLoopback && verifyKeyTail(presentedLoopback) && gateDevice(deviceId) === DEVICE_GATE.unknown) {
        approveDeviceSession(deviceId);
        logger.info(`loopback workspace device admitted for this session (key TAIL verified): ${deviceId.slice(0, 8)}`);
        pushUiLogDebug(`Loopback workspace admitted (session): ${deviceId.slice(0, 8)} (key TAIL verified)`);
      }
    }

    trackConnection(socket.id, ip, deviceId);
    pushUiLogDebug(`Client connected: ${ip} (device: ${deviceId?.slice(0, 8) || "none"})`);

    socket.on("disconnect", (reason) => {
      untrackConnection(socket.id);
      removePendingApproval(socket.id);
      // A dropped carrier is a switch, not a departure, while another carrier is up.
      const conn = socket.data?.conn;
      if (conn) {
        conn.detach("ws");
        if (!conn.connected) conn.close("carrier-gone");
      }
      const pm = socket.data?.protocol;
      pushUiLogDebug(`Client disconnected: ${ip} (${reason}) pm=${pm?._deviceId?.slice(0, 12) || "none"} remoteAttached=${!!socket.data?.remoteAttached}`);
      // PM cleanup is deferred to remoteSocket's grace timer when remote was attached.
      if (pm && !socket.data?.remoteAttached) disposeProtocol(pm);
    });

    // Re-runnable for the offer grace wait; synchronous so nothing slips between decide and act.
    const route = () => {
      if (!socket.connected) return; // disconnected during the grace wait
      const peerId = socket.handshake.auth?.peerId || null;
      const holdForApproval = () => {
        // Unlocked meanwhile by the device's own RTC release — nothing to hold.
        if (socket.data.approved) return;
        // An RTC peer may have raised the entry first — decide how this ws socket joins it.
        const prevId = getPendingSocketId(deviceId);
        if (prevId && !rtcPeerId(prevId)) {
          pushUiLogDebug(`Device ${deviceId?.slice(0, 8)} already pending, ignoring duplicate`);
          socket.disconnect(true);
          return;
        }
        // Entry moved rtc→ws: the modal is already up — re-notifying would pop it twice.
        const moved = !!prevId;
        if (prevId) removePendingApproval(prevId);

        // Reached only with the key proven; the wait is for the client's listeners.
        onClientReady(socket, () => {
          // Approved while waiting (host used the rtc modal) — nothing to request
          if (socket.data.approved || !socket.connected) return;
          // Same request already on screen — hand it over without re-raising it.
          if (moved) {
            addPendingApproval(socket.id, { deviceId, ip });
            verdictEmit(socket, "device:pendingApproval");
            return;
          }
          askHostToApprove(deviceId, {
            socketId: socket.id,
            ip,
            notify: () => verdictEmit(socket, "device:pendingApproval")
          });
        });
      };

      // Attach to the live RTC session instead of building a second PM.
      const attachToRtcSession = (rtcSession) => {
        // The session is the authority — never mint a verdict here.
        const conn = rtcSession.data.conn;
        socket.data.conn = conn;
        socket.data.approved = !!conn?.active;
        socket.data.rtcHost = rtcSession;
        // The PM may still be mid-build; data.ready keeps an early WS from attaching to nothing.
        Promise.resolve(rtcSession.data.ready)
          .then(() => rtcSession.data.protocol?.attachSocket(socket))
          // attachSocket builds the adapter — registering earlier hands over a null.
          .then(() => conn?.attach("ws", rtcSession.data.protocol?._adapters?.get("ws") || null))
          // terminal:ready rode RTC and could race listener binding — re-emit, but only when active.
          .then(() => { if (conn?.active) socket.emit("terminal:ready"); })
          .catch((e) => pushUiLog(`RTC session attachSocket failed: ${e.message}`));
        pushUiLogDebug(`Tunnel attached to RTC session: ${deviceId.slice(0, 8)}...`);
        announceAdmitted(socket);
      };

      // A buffered RTC offer will build a session shortly — grace-wait instead of a duplicate PM.
      const rtcSession = peerId ? rtcSessions.get(peerId) : null;
      if (!rtcSession && peerId && !socket.data._rtcWaited && hasPendingOffer(peerId)) {
        socket.data._rtcWaited = true;
        pushUiLogDebug(`WS first, RTC offer pending → grace 500ms (device ${deviceId.slice(0, 8)})`);
        setTimeout(route, 500);
        return;
      }

      // One decision, one action per outcome — where the session lives is routing, decided after.
      const verdict = askGate(socket, deviceId);

      // Waiting on the KEY, not the host: hold unapproved until the proof or the deadline settles it.
      if (verdict.decision === ADMISSION.hold && verdict.step === "auth") {
        // No id to prove: onTailProven runs the retry NOW and route() re-enters this
        // branch synchronously until the stack dies. Such a socket can never be admitted.
        if (!deviceId) {
          logger.warn(`route: socket with no device id (${ip}) — disconnecting`);
          socket.disconnect(true);
          return;
        }
        logger.info(`route: awaiting TAIL proof device=${deviceId?.slice(0, 8) || "no-id"}`);
        onTailProven(deviceId, () => route(), () => {
          rejectDeviceTail(socket, deviceId, TAIL_REJECT_REASON.timeout);
        });
        return;
      }

      switch (verdict.decision) {
        case ADMISSION.admit:
          // A live session owns the PM — attach; admission already answered the approval check.
          if (rtcSession) return void attachToRtcSession(rtcSession);
          pushUiLogDebug(`Device admitted: ${deviceId?.slice(0, 8)}...`);
          unlockSocket(socket);
          return;

        case ADMISSION.reject: {
          // A failed proof is not the host-kick flow: answer after the penalty, then close every carrier.
          if (socket.data?.tailReject) return void rejectDeviceTail(socket, deviceId);
          // Previously rejected — keep socket unapproved, no modal, update socketId for later approve
          updateRejectedSocket(deviceId, socket.id, ip);
          pushUiLog(`Rejected device reconnected: ${deviceId.slice(0, 8)} — waiting in Clients list`);
          verdictEmit(socket, "device:rejected");
          pushUiEvent("deviceApproval", { action: "refresh" });
          return;
        }

        default:
          logger.info(`route: hold for approval device=${deviceId?.slice(0, 8) || "no-id"}`);
          pushUiLog(`Device needs approval: ${deviceId?.slice(0, 8) || "no-id"}`);
          holdForApproval();
      }
    };
    route();
  });

  setupTerminalSocket(io, loadApiKey());

  ioInstance = io;
  return io;
}
