// Transport server: WS entry point + future protocols
import { Server } from "socket.io";
import { readFileSync } from "fs";
import { join } from "path";
import { initSignalingGlobal, setOfferFallback, sendSignaling, dropPending, pendingPeersOf, onSignalingReady, hasPendingOffer, retrySignalingNow } from "../lib/signalingGlobal.js";
import { VirtualSocket } from "./VirtualSocket.js";
import { PATHS, LOCAL_UI_ORIGINS, LOCAL_UI_DEVICE_ID } from "../lib/constants.js";
import { verifyLocalToken } from "../lib/localToken.js";
import { ProtocolManager } from "./ProtocolManager.js";
import { SIGNALING_ERRORS } from "../lib/transportConstants.js";
import { registerProtocol, unregisterProtocol, activeProtocols, disableAllRtc, notifyRtcEnabled } from "./broadcast.js";
import { REMOTE_CONFIG } from "../features/remote/REMOTE_CONFIG.js";
import { setupTerminalSocket, setupTerminalHandlers } from "../features/terminal/terminalSocket.js";
import { checkRemoteAvailable } from "../features/remote/remoteSocket.js";
import { setupFileExplorerHandlers } from "../features/fileExplorer/fileExplorerSocket.js";
import { setupClipboardHandlers } from "../features/clipboard/clipboardSocket.js";
import { setupQuotaTrackerHandlers } from "../features/quotaTracker/quotaTrackerSocket.js";
import { setupBackgroundHandlers } from "../features/terminal/backgroundSocket.js";
import { trackConnection, untrackConnection, pushUiLog, pushUiLogDebug, clearOneTimeKey, pushUiEvent, setRemoteAvailable, pushTransportState } from "../api/ui.js";
import {
  loadApprovedDevices,
  isDeviceApproved,
  isDevicePending,
  gateDevice,
  approveDevice,
  addPendingApproval,
  removePendingApproval,
  getPendingApproval,
  getPendingSocketId,
  markDeviceRejected,
  updateRejectedSocket,
  clearRejectedDevice,
  loadAutoApprove
} from "../lib/deviceApproval.js";
import { handleDeviceEnroll, decideAdmission } from "../lib/deviceAuth.js";
import { headOf, tailOf } from "../cli/utils/apiKey.js";

function loadApiKey() {
  try {
    const keysFile = join(PATHS.ROOT, "keys.json");
    const data = JSON.parse(readFileSync(keysFile, "utf8"));
    return data.key || null;
  } catch {
    return null;
  }
}

// How often to re-read keys.json so a key regenerated by the CLI process is
// picked up here (see the watcher in startTransportServer).
const KEY_WATCH_INTERVAL_MS = 5000;

let ioInstance = null;

export function getIO() {
  return ioInstance;
}

/** Setup all per-socket features on an approved socket (single entry point).
 * Order matters: transport bus MUST be ready before terminal/remote handlers so the
 * first tile frame isn't dropped (black canvas). File + terminal + remote all live here.
 * Emits "terminal:ready" once handlers are registered so the client can fetch sessions
 * without racing the async setup (F5 was landing getSessions before getSessions handler). */
async function setupSocketFeatures(socket) {
  // Clear one-time key if used
  if (socket.handshake.auth?.tempKey) {
    pushUiLog("One-time key used \u2014 clearing from UI");
    clearOneTimeKey();
  }
  await attachTransportBus(socket);
  // Pairing enrollment \u2014 registered before any await below: the client sends it
  // the moment its RTC opens. Valid only while a pairing code is live, and the
  // TAIL it delivers goes out on the RTC carrier only.
  socket.on("device:enroll", (data) => handleDeviceEnroll(socket, data));
  // RTC-only session \u2014 same admission rules as the WS path (decideAdmission),
  // but there is no modal to fall back to here: an impostor session is dropped.
  if (socket.isVirtual) {
    const deviceId = socket.handshake.auth?.deviceId || null;
    const ok = decideAdmission(socket, deviceId) === "admit";
    if (!ok) {
      pushUiLog(`Device not admitted (RTC): ${socket.handshake.auth?.deviceId?.slice(0, 8)} \u2014 dropping session`);
      socket.disconnect();
      return;
    }
  }
  setupFileExplorerHandlers(socket);
  setupClipboardHandlers(socket);
  setupQuotaTrackerHandlers(socket);
  setupBackgroundHandlers(socket);
  await setupTerminalHandlers(socket, ioInstance, loadApiKey());
  socket.emit("terminal:ready");
}

/** Create connection-level PM and route socket.emit through it (DRY transport bus).
 * Awaits pm.init() so the ws adapter is ready before tiles stream (else first frame
 * is dropped by sendTiles while checksums are already marked sent → black canvas). */
async function attachTransportBus(socket) {
  if (socket.data.protocol) return;
  const { webrtc, streaming } = REMOTE_CONFIG;
  const pm = new ProtocolManager(socket, {
    enableWebRTC: webrtc.enableWebRTC,
    apiKey: webrtc.enableTurn ? headOf(loadApiKey()) : null,
    turnApiUrl: webrtc.enableTurn ? webrtc.turnApiUrl : null,
    turnRefreshInterval: webrtc.turnRefreshInterval,
    dcMaxMessageSize: webrtc.dcMaxMessageSize,
    dcChunkSize: webrtc.dcChunkSize,
    dcMaxTilesPerFrame: webrtc.dcMaxTilesPerFrame,
    answerTimeout: webrtc.answerTimeout,
    maxControlBuffer: webrtc.maxControlBuffer,
    wsChunkSize: streaming.chunkSize,
    // DO signaling relay — room = client deviceId, gated by apiKey on the Worker.
    signaling: {
      // Always route by peerId (deviceId:tab) — the client's offer arrives with
      // from=peerId, so the PM must register its handler under that exact key or
      // signalingGlobal won't find it and will spawn a second RTC-only PM (→ the
      // two-PM duplicate-output bug). VirtualSocket has .peerId; a real socket.io
      // socket carries it in handshake.auth.peerId (set by the client).
      deviceId: socket.peerId || socket.handshake.auth?.peerId || socket.handshake.auth?.deviceId || null,
      doUrl: webrtc.signalingDoUrl,
      apiKey: loadApiKey()
    }
  });
  socket.data.protocol = pm;
  // Virtual session: RTC dying with no WS fallback means the session is over.
  if (socket.isVirtual) {
    pm._onDead = () => {
      pushUiLogDebug(`RTC session closed: ${socket.handshake.auth?.deviceId?.slice(0, 8)}...`);
      try { pm.close(); } catch {}
      unregisterProtocol(pm);
      socket.disconnect();
    };
  }
  registerProtocol(pm);
  pm.attachAsBus(socket);
  try {
    await pm.init(); // also arms DO signaling (no gap between the two)
  } catch (e) {
    console.error("[transport] pm init failed:", e.message);
  }
}

// RTC-only sessions keyed by client peerId ("deviceId:tab") — created when an
// offer arrives over DO signaling before the tunnel brought socket.io up.
const rtcSessions = new Map();

// Debug toggle — when false, the agent refuses RTC offers so clients fall back
// to the tunnel. Lets you test the fallback path without pulling the network.
let rtcTestDisabled = false;

export function isRtcTestDisabled() { return rtcTestDisabled; }
export function setRtcTestDisabled(disabled) {
  rtcTestDisabled = disabled;
  if (!disabled) {
    // RTC re-enabled: tell clients to clear their stop-retry flag and renegotiate.
    notifyRtcEnabled();
    return;
  }
  // RTC now lives inside the WS-hosted PM (not rtcSessions), so tear it down
  // across every active PM. The client then falls back to the WS tunnel.
  disableAllRtc();
  // Also clear VirtualSocket RTC sessions (RTC-first offer-before-WS case).
  for (const [peerId, vs] of rtcSessions) {
    try {
      const pm = vs.data?.protocol;
      try { vs.disconnect(); } catch {}
      if (pm) { try { pm.close(); } catch {} unregisterProtocol(pm); }
    } catch {}
    rtcSessions.delete(peerId);
    pushUiLogDebug(`RTC test-disabled: killed session ${peerId?.slice(0, 8)}`);
  }
}

// Synthetic socketId for a DO peer — lets pending approvals and the Clients
// list address an RTC session with the same key shape as a socket.io socket.
const rtcSocketId = (peerId) => `rtc-${peerId}`;
const rtcPeerId = (socketId) => (socketId.startsWith("rtc-") ? socketId.slice(4) : null);
const sendSignalingTo = (peerId, msg) => sendSignaling({ ...msg, to: peerId });

// clientReady can beat route()'s grace wait — the flag is stamped by a listener
// bound at connection, so a late once() doesn't miss the event.
function onClientReady(socket, fn) {
  if (socket.data.clientReady) fn();
  else socket.once("device:clientReady", fn);
}

/** Route an RTC offer that arrived over DO signaling through the shared gate:
 * approved → build the session; unknown → raise the same approval modal as
 * the socket.io path (the offer stays buffered until Approve); rejected →
 * tell the client. */
function handleRtcOffer(peerId) {
  if (!peerId) return;
  // Debug toggle — refuse RTC so the client falls back to the tunnel immediately.
  if (rtcTestDisabled) {
    sendSignalingTo(peerId, { type: "error", message: "rtc-disabled" });
    return;
  }
  // peerId = "deviceId:tab" — one session per tab, approval per device.
  const deviceId = peerId.split(":")[0];

  const existing = rtcSessions.get(peerId);
  if (existing) {
    // Live (or still building — protocol not attached yet) → the offer is
    // already routed to its PM. Only a closed PM is stale and worth rebuilding.
    if (!existing.data.protocol?._closed) return;
    pushUiLogDebug(`Stale RTC session ${deviceId.slice(0, 8)} — rebuilding`);
    try { existing.disconnect(); } catch {}
    rtcSessions.delete(peerId);
  }

  // A live WS socket for this peer will register its signaling handler and
  // consume the buffered offer — spawning here would build a duplicate PM.
  const hasWsHost = hasLiveWsForPeer(peerId);

  switch (gateDevice(deviceId)) {
    case "approved":
      if (hasWsHost) return;
      return void startRtcSession(peerId, deviceId);

    case "rejected":
      updateRejectedSocket(deviceId, rtcSocketId(peerId), "rtc");
      sendSignalingTo(peerId, { type: "error", message: SIGNALING_ERRORS.rejected });
      dropPending(peerId); // nothing will consume it — don't hold the SDP in RAM
      pushUiLog(`Rejected device via RTC: ${deviceId.slice(0, 8)} — waiting in Clients list`);
      pushUiEvent("deviceApproval", { action: "refresh" });
      return;

    case "auto":
      // Routing only — admission (TAIL proof, grandfathering) is decided by
      // decideAdmission inside the session build, which drops an impostor.
      return void autoApproveAndRelease(deviceId);

    default:
      // Unknown device — same pending flow as socket.io. The offer stays buffered
      // in signalingGlobal; releaseDevice builds the session and flushes it.
      // Tell the client so it shows the "waiting for approval" screen (the socket.io
      // path sends device:pendingApproval; over DO the only channel is signaling).
      sendSignalingTo(peerId, { type: "error", message: SIGNALING_ERRORS.pending });
      // Approval is per device — a second tab reuses the first tab's pending entry.
      if (isDevicePending(deviceId)) return;
      addPendingApproval(rtcSocketId(peerId), { deviceId, ip: "rtc", peerId });
      pushUiLog(`Unknown device (RTC): ${deviceId.slice(0, 8)} — waiting for approval`);
      pushUiEvent("deviceApproval", { socketId: rtcSocketId(peerId), deviceId, ip: "rtc", action: "pending" });
  }
}

/** True when a connected socket.io socket already carries this peerId — its PM
 * (existing or mid-setup) owns the buffered offer for that tab. */
function hasLiveWsForPeer(peerId) {
  for (const s of ioInstance?.sockets.sockets.values() || []) {
    if (s.connected && s.handshake.auth?.peerId === peerId) return true;
  }
  return false;
}

/** Unlock one waiting WS socket. Idempotent — a second unlock (double-tap on
 * Approve, modal racing the Clients list) must not re-run feature setup. */
function unlockSocket(socket) {
  if (socket.data.approved || socket.data.unlocking) return Promise.resolve();
  socket.data.approved = true;
  socket.data.unlocking = true;
  onClientReady(socket, () => socket.emit("device:approved"));
  const done = setupSocketFeatures(socket)
    .catch((e) => pushUiLog(`Feature setup failed: ${e.message}`))
    .finally(() => { socket.data.unlocking = false; });
  return done;
}

/** Approve is per device — unlock every carrier waiting on it. WS setups run
 * first so their signaling handlers consume the buffered offers; only offers
 * still unconsumed afterwards (no WS for that tab, or setup failed) spawn an
 * RTC-only session. This ordering is what prevents the double-PM. */
async function releaseDevice(deviceId) {
  if (!deviceId) return;
  const key = getPendingSocketId(deviceId);
  if (key) removePendingApproval(key);
  const setups = [];
  for (const socket of ioInstance?.sockets.sockets.values() || []) {
    if (socket.handshake.auth?.deviceId !== deviceId || socket.data.approved) continue;
    setups.push(unlockSocket(socket));
  }
  await Promise.allSettled(setups);
  for (const peerId of pendingPeersOf(deviceId)) startRtcSession(peerId, deviceId);
}

/** Auto-approve intake path, shared by both carriers. For v2 keys the caller
 * has already verified the key-TAIL proof — the server only holds the HEAD and
 * can never pass it, which is what makes auto-approve safe again. */
function autoApproveAndRelease(deviceId) {
  approveDevice(deviceId);
  clearRejectedDevice(deviceId);
  pushUiLog(`Auto-approved device: ${deviceId.slice(0, 8)}...`);
  pushUiEvent("deviceApproval", { action: "refresh" });
  releaseDevice(deviceId);
}

/** Pending entry by socketId, falling back to the device's current entry.
 * Approvals move between carriers (rtc-… → real socket), so an exact-id miss
 * (stale modal) must not silently fail the click. Returns { key, …entry }. */
function resolvePending(socketId) {
  const direct = getPendingApproval(socketId);
  if (direct) return { key: socketId, ...direct };
  const deviceId = rtcPeerId(socketId)?.split(":")[0]
    || ioInstance?.sockets.sockets.get(socketId)?.handshake.auth?.deviceId
    || null;
  const key = deviceId ? getPendingSocketId(deviceId) : null;
  const entry = key ? getPendingApproval(key) : null;
  return entry ? { key, ...entry } : null;
}

/** Fire-and-forget build — every caller is a sync signaling/approval path. */
function startRtcSession(peerId, deviceId) {
  buildRtcSession(peerId, deviceId).catch((e) => {
    const stale = rtcSessions.get(peerId);
    if (stale) {
      try { stale.data.protocol?.close(); } catch {}
      unregisterProtocol(stale.data.protocol);
      stale.disconnect();
    }
    rtcSessions.delete(peerId);
    pushUiLog(`RTC session failed: ${e.message}`);
  });
}

/** Build the virtual socket + PM for an approved RTC peer. */
async function buildRtcSession(peerId, deviceId) {
  if (rtcSessions.has(peerId)) return;
  const socket = new VirtualSocket({ deviceId, peerId, apiKey: loadApiKey() });
  socket.data.approved = true;
  socket.data.rtcSession = true;
  // Published to the map BEFORE its PM exists, so anyone who picks it up must
  // wait on this instead of reading .data.protocol (which is still undefined
  // and would silently no-op through an optional chain).
  let markReady;
  socket.data.ready = new Promise((resolve) => { markReady = resolve; });
  rtcSessions.set(peerId, socket);
  trackConnection(socket.id, "rtc", deviceId, "rtc");
  socket.on("disconnect", () => {
    if (rtcSessions.get(peerId) === socket) rtcSessions.delete(peerId);
    untrackConnection(socket.id);
    markReady(); // never leave a waiter hanging on a dead session
  });
  pushUiLogDebug(`RTC session: ${deviceId.slice(0, 8)}...`);
  try {
    await setupSocketFeatures(socket);
  } finally {
    markReady();
  }
  // Client waits for this before loading sessions (mirrors the socket.io path).
  socket.once("device:clientReady", () => socket.emit("device:approved"));
  socket.emit("device:approved");
}

/** Approve a pending device (approval modal or Clients list) — one path for
 * both carriers. Resolution falls back to the device's current entry so a
 * stale modal socketId (moved rtc→ws) still lands. */
export function approveSocketDevice(socketId) {
  if (!ioInstance) return false;
  const pending = resolvePending(socketId);
  if (!pending) return false;

  approveDevice(pending.deviceId);
  clearRejectedDevice(pending.deviceId);
  pushUiLog(`Device approved: ${pending.deviceId.slice(0, 8)}...`);

  releaseDevice(pending.deviceId); // also clears the device's pending entry
  pushUiEvent("deviceApproval", { action: "refresh" });
  return true;
}

/** Approve a previously-rejected device by deviceId (from Clients list) */
export function approveRejectedDevice(deviceId) {
  if (!ioInstance || !deviceId) return false;

  approveDevice(deviceId);
  clearRejectedDevice(deviceId);
  pushUiLog(`Device approved from pending: ${deviceId.slice(0, 8)}...`);

  releaseDevice(deviceId);
  pushUiEvent("deviceApproval", { action: "refresh" });
  return true;
}

/** Disconnect all active sockets belonging to a deviceId (device stays approved) */
export function disconnectDeviceSockets(deviceId) {
  const io = ioInstance;
  if (!io || !deviceId) return 0;
  let count = 0;
  for (const socket of io.sockets.sockets.values()) {
    if (socket.handshake.auth?.deviceId === deviceId) {
      socket.disconnect(true);
      count++;
    }
  }
  // Kill every PM serving this device. The RTC peer may live INSIDE a ws-socket's
  // PM (not in rtcSessions), and the socket's own disconnect handler defers PM
  // cleanup when remote was attached — an explicit kick must close it now, else
  // the client keeps a live data channel and never re-requests approval.
  for (const pm of activeProtocols()) {
    if (pm._closed) continue;
    if (pm._deviceId?.split(":")[0] !== deviceId) continue;
    try { pm.close(); } catch {}
    unregisterProtocol(pm);
    count++;
  }
  // RTC-only sessions have no socket.io entry — kill them by peerId prefix.
  for (const [peerId, vs] of rtcSessions) {
    if (peerId.split(":")[0] !== deviceId) continue;
    try { vs.data.protocol?.close(); } catch {}
    unregisterProtocol(vs.data.protocol);
    dropPending(peerId);
    vs.disconnect();
    count++;
  }
  if (count) pushUiLogDebug(`Disconnected ${count} socket(s) for device ${deviceId.slice(0, 8)}...`);
  return count;
}

/** Reject a pending device by socketId (modal) — notifies both carriers,
 * remembers the rejection in RAM for the Clients list. */
export function rejectSocketDevice(socketId) {
  if (!ioInstance) return false;

  const pending = resolvePending(socketId);
  const socket = ioInstance.sockets.sockets.get(socketId);
  removePendingApproval(pending?.key || socketId);

  if (pending?.deviceId) {
    markDeviceRejected(pending.deviceId, { ip: pending.ip, socketId });
  }

  if (socket) {
    socket.emit("device:rejected");
    socket.disconnect(true);
  }

  // RTC peer — no socket to notify; answer over DO and drop the buffered offer.
  const peerId = pending?.peerId || rtcPeerId(socketId);
  if (peerId) {
    sendSignalingTo(peerId, { type: "error", message: SIGNALING_ERRORS.rejected });
    dropPending(peerId);
  }

  pushUiEvent("deviceApproval", { action: "refresh" });
  pushUiLog(`Device rejected: ${pending?.deviceId?.slice(0, 8) || "unknown"}...`);
  return true;
}

export async function startTransportServer(server) {
  // Load approved devices + auto-approve setting from disk
  loadApprovedDevices();
  loadAutoApprove();

  // Join the DO signaling room (room = apiKey) at server boot — independent of
  // any socket.io/tunnel connection. Lets RTC establish before the tunnel is up.
  initSignalingGlobal(headOf(loadApiKey()));
  // The TUI regenerates the key in a SEPARATE process (cli/core/cmdPoller), so
  // this one only learns about it through keys.json. Re-reading on a timer keeps
  // the room in sync — initSignalingGlobal no-ops when the key is unchanged.
  setInterval(() => {
    const key = headOf(loadApiKey());
    if (key) initSignalingGlobal(key);
  }, KEY_WATCH_INTERVAL_MS);
  // Offer with no PM → build an RTC-only session so login works without a tunnel.
  setOfferFallback(handleRtcOffer);
  onSignalingReady(() => pushTransportState());

  const io = new Server(server, {
    cors: {
      origin: "*",
      methods: ["GET", "POST"],
      credentials: true,
      allowedHeaders: ["*"]
    },
    transports: ["websocket", "polling"],
    allowEIO3: true,
    allowUpgrades: true,
    pingTimeout: 60000,
    pingInterval: 25000,
    maxHttpBufferSize: 1e8,
    perMessageDeflate: { threshold: 1024 }
  });

  // Check remote availability at startup
  const hasRemote = await checkRemoteAvailable();
  setRemoteAvailable(hasRemote);

  // Track connections + device approval
  io.on("connection", (socket) => {
    // A client got through, so the network is up: revive the DO relay if it
    // gave up during boot (agent started before wifi). Throttled inside.
    retrySignalingNow();
    const ip = socket.handshake.headers["x-forwarded-for"] || socket.handshake.address || "unknown";
    const deviceId = socket.handshake.auth?.deviceId || null;

    // clientReady can beat route()'s grace wait — track it so a late once() doesn't miss the event
    socket.data.clientReady = false;
    socket.on("device:clientReady", () => { socket.data.clientReady = true; });

    // Block all events from unapproved sockets (except device:clientReady)
    socket.data.approved = false;
    socket.use((packet, next) => {
      if (socket.data.approved) return next();
      const event = packet[0];
      if (event === "device:clientReady" || event === "disconnect") return next();
      return next(new Error("Device not approved"));
    });

    // Trusted local UI — valid ephemeral token + loopback + same-origin (or non-browser).
    // Resists CSWSH: a malicious page can't read the token (loopback + origin-guarded endpoint).
    const rawAddr = socket.handshake.address || "";
    const isLoopback = rawAddr === "127.0.0.1" || rawAddr === "::1" || rawAddr === "::ffff:127.0.0.1";
    const isTunnel = !!socket.handshake.headers["cf-connecting-ip"];
    const origin = socket.handshake.headers.origin;
    const originOk = !origin || LOCAL_UI_ORIGINS.includes(origin);
    if (!isTunnel && isLoopback && originOk && verifyLocalToken(socket.handshake.auth?.localToken)) {
      socket.data.approved = true;
      socket.data.localUi = true;
      pushUiLogDebug("Local UI connected — trusted (token)");
      // emits "terminal:ready" when handlers registered
      setupSocketFeatures(socket).catch((e) => pushUiLog(`Feature setup failed: ${e.message}`));
      return; // do not track in Clients list
    }

    // Reserved local-ui deviceId that failed trust check → spoof attempt, reject.
    if (deviceId === LOCAL_UI_DEVICE_ID) {
      pushUiLog(`Rejected untrusted local-ui socket from ${ip}`);
      socket.disconnect(true);
      return;
    }

    trackConnection(socket.id, ip, deviceId);
    pushUiLogDebug(`Client connected: ${ip} (device: ${deviceId?.slice(0, 8) || "none"})`);

    socket.on("disconnect", (reason) => {
      untrackConnection(socket.id);
      removePendingApproval(socket.id);
      const pm = socket.data?.protocol;
      pushUiLogDebug(`Client disconnected: ${ip} (${reason}) pm=${pm?._deviceId?.slice(0, 12) || "none"} remoteAttached=${!!socket.data?.remoteAttached}`);
      // PM cleanup deferred: remoteSocket grace timer handles it if remote was attached;
      // otherwise close immediately
      if (pm && !socket.data?.remoteAttached) {
        try { pm.close(); } catch {}
        unregisterProtocol(pm);
      }
    });

    // Route this socket: attach to an existing RTC session, wait for an in-flight
    // one, or go through the normal approval + setup. Wrapped in `route()` so the
    // pending-offer grace can re-run it after a brief wait (WS usually arrives
    // before the RTC offer; without waiting we'd build a second PM and broadcast
    // duplicate output to this client).
    // Synchronous by design: admission is decided from the handshake, so there
    // is no await between "decide" and "act" for another event to slip into.
    const route = () => {
      if (!socket.connected) return; // disconnected during the grace wait
      const peerId = socket.handshake.auth?.peerId || null;
      const holdForApproval = () => {
        // Unlocked while this path was deciding (a releaseDevice from the
        // device's own RTC session) — nothing left to hold.
        if (socket.data.approved) return;
        // Already pending — an RTC peer raised it first. Hand the entry to this
        // real socket so Approve unlocks it and the client gets the waiting modal.
        const prevId = getPendingSocketId(deviceId);
        if (prevId && !rtcPeerId(prevId)) {
          pushUiLogDebug(`Device ${deviceId?.slice(0, 8)} already pending, ignoring duplicate`);
          socket.disconnect(true);
          return;
        }
        // Entry moved rtc→ws: the agent modal is already up with the old id
        // (resolvePending accepts it) — re-notifying would pop the modal twice.
        const moved = !!prevId;
        if (prevId) removePendingApproval(prevId);

        addPendingApproval(socket.id, { deviceId, ip });

        // Wait for client to signal ready before emitting approval request
        onClientReady(socket, () => {
          // Approved while waiting (host used the rtc modal) — nothing to request
          if (socket.data.approved) return;
          socket.emit("device:pendingApproval");
          if (!moved) {
            pushUiEvent("deviceApproval", {
              socketId: socket.id,
              deviceId,
              ip,
              action: "pending"
            });
          }
        });
      };

      const rtcSession = peerId ? rtcSessions.get(peerId) : null;
      if (rtcSession && isDeviceApproved(deviceId)) {
        // The RTC-only session was admitted without a TAIL (a VirtualSocket has
        // no socket.io handshake to carry one). This WS DOES carry it, so check
        // here — otherwise connecting RTC-first would skip the TAIL entirely.
        if (decideAdmission(socket, deviceId) !== "admit") {
          pushUiLog(`Device TAIL check failed on RTC attach: ${deviceId.slice(0, 8)}`);
          return void holdForApproval();
        }
        socket.data.approved = true;
        socket.data.rtcHost = rtcSession;
        // The session may still be building (its PM is assigned inside
        // setupSocketFeatures). Waiting on data.ready is what keeps a WS that
        // arrives mid-build from attaching to nothing and hanging approved.
        Promise.resolve(rtcSession.data.ready)
          .then(() => rtcSession.data.protocol?.attachSocket(socket))
          // The virtual session's terminal:ready rode RTC and could race the client's
          // listener binding — re-emit on this socket so the session list always gets a
          // fetch trigger (client handler is idempotent).
          .then(() => socket.emit("terminal:ready"))
          .catch((e) => pushUiLog(`RTC session attachSocket failed: ${e.message}`));
        pushUiLogDebug(`Tunnel attached to RTC session: ${deviceId.slice(0, 8)}...`);
        onClientReady(socket, () => socket.emit("device:approved"));
        return;
      }

      // WS arrived first but an RTC offer is buffered in signalingGlobal and will
      // build a session momentarily. Wait one grace window instead of spawning a
      // second PM now (which would duplicate-broadcast to this client).
      if (peerId && !socket.data._rtcWaited && hasPendingOffer(peerId)) {
        socket.data._rtcWaited = true;
        pushUiLogDebug(`WS first, RTC offer pending → grace 500ms (device ${deviceId.slice(0, 8)})`);
        setTimeout(route, 500);
        return;
      }


      // One decision for every carrier — see lib/deviceAuth.decideAdmission.
      switch (decideAdmission(socket, deviceId)) {
        case "admit":
          pushUiLogDebug(`Device admitted: ${deviceId?.slice(0, 8)}...`);
          unlockSocket(socket);
          return;

        case "reject":
          // Previously rejected — keep socket unapproved, no modal, update socketId for later approve
          updateRejectedSocket(deviceId, socket.id, ip);
          pushUiLog(`Rejected device reconnected: ${deviceId.slice(0, 8)} — waiting in Clients list`);
          socket.emit("device:rejected");
          pushUiEvent("deviceApproval", { action: "refresh" });
          return;

        default:
          pushUiLog(`Device needs approval: ${deviceId?.slice(0, 8) || "no-id"}`);
          holdForApproval();
      }
    };
    route();
  });

  // Init terminal broadcast + serverInfo builder (per-socket handlers wired in setupSocketFeatures)
  setupTerminalSocket(io, loadApiKey());

  ioInstance = io;
  return io;
}
